src/Entity/Ingredient.php
<?php

namespace App\Entity;

use App\Repository\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: IngredientRepository::class)]
class Ingredient
{
    const WHERE_TO_KEEP_OPTIONS = [
        'closet' => 'Placard',
        'fridge' => 'Frigidaire',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: 'Le nom de l\'ingrédient est requis.', normalizer: 'trim')]
    #[Assert\Length(max: 255, maxMessage: "Le nom de l'ingrédient ne peut excéder 255 caractères.")]
    private ?string $name = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Choice(callback: 'getWhereToKeepOptions', message: 'Cette option n\'est pas valide.')]
    private ?string $whereToKeep = null;

    #[ORM\OneToMany(mappedBy: 'ingredient', targetEntity: RecipeIngredient::class)]
    private Collection $recipeIngredients;

    #[ORM\ManyToOne(inversedBy: 'ingredients')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull(message: 'La catégorie est requise.')]
    #[Assert\Type(type: IngredientCategory::class, message: "Cette valeur n'est pas du bon type.")]
    #[Assert\Valid]
    private ?IngredientCategory $category = null;

    #[ORM\ManyToMany(targetEntity: IngredientTag::class, inversedBy: 'ingredients')]
    #[ORM\OrderBy(['name' => 'ASC'])]
    #[Assert\Valid]
    #[Assert\All([
        new Assert\Type(type: IngredientTag::class, message: "Cette valeur n'est pas du bon type."),
    ])]
    private Collection $tags;

    #[ORM\ManyToOne(inversedBy: 'ingredients')]
    private ?QuantityType $defaultQuantityType = null;

    #[ORM\OneToMany(mappedBy: 'ingredient', targetEntity: StockIngredient::class)]
    private Collection $stockIngredients;

    public function __construct()
    {
        $this->recipeIngredients = new ArrayCollection();
        $this->tags = new ArrayCollection();
        $this->stockIngredients = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getWhereToKeep(): ?string
    {
        return $this->whereToKeep;
    }

    public static function getWhereToKeepOptions(): array
    {
        return array_merge(
            ['Je ne sais pas' => null],
            array_flip(self::WHERE_TO_KEEP_OPTIONS)
        );
    }

    public function getWhereToKeepLabel(): ?string
    {
        if ($this->whereToKeep) {
            return self::WHERE_TO_KEEP_OPTIONS[$this->whereToKeep];
        }

        return null;
    }

    public function setWhereToKeep(?string $whereToKeep): self
    {
        $this->whereToKeep = $whereToKeep;

        return $this;
    }

    /**
     * @return Collection<int, RecipeIngredient>
     */
    public function getRecipeIngredients(): Collection
    {
        return $this->recipeIngredients;
    }

    public function addRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if (!$this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients->add($recipeIngredient);
            $recipeIngredient->setIngredient($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if ($this->recipeIngredients->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getIngredient() === $this) {
                $recipeIngredient->setIngredient(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?IngredientCategory
    {
        return $this->category;
    }

    public function setCategory(?IngredientCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, IngredientTag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(IngredientTag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags->add($tag);
        }

        return $this;
    }

    public function removeTag(IngredientTag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getDefaultQuantityType(): ?QuantityType
    {
        return $this->defaultQuantityType;
    }

    public function setDefaultQuantityType(?QuantityType $defaultQuantityType): self
    {
        $this->defaultQuantityType = $defaultQuantityType;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return Collection<int, StockIngredient>
     */
    public function getStockIngredients(): Collection
    {
        return $this->stockIngredients;
    }

    public function addStockIngredient(StockIngredient $stockIngredient): self
    {
        if (!$this->stockIngredients->contains($stockIngredient)) {
            $this->stockIngredients->add($stockIngredient);
            $stockIngredient->setIngredient($this);
        }

        return $this;
    }

    public function removeStockIngredient(StockIngredient $stockIngredient): self
    {
        if ($this->stockIngredients->removeElement($stockIngredient)) {
            // set the owning side to null (unless already changed)
            if ($stockIngredient->getIngredient() === $this) {
                $stockIngredient->setIngredient(null);
            }
        }

        return $this;
    }
}

src/Controller/Ingredient/IngredientCategoryController.php
<?php

namespace App\Controller\Ingredient;

use App\Entity\IngredientCategory;
use App\Form\IngredientCategoryType;
use App\Repository\IngredientCategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ingredient-category')]
class IngredientCategoryController extends AbstractController
{
    private IngredientCategoryRepository $repository;

    public function __construct(IngredientCategoryRepository $repository)
    {
        $this->repository = $repository;
    }

    #[Route('/', name: 'app_ingredient_category_index', methods: ['GET'])]
    public function index(): Response
    {
        $categories = $this->repository->findBy([], ['position' => 'ASC']);

        return $this->render('ingredient_category/index.html.twig', ['categories' => $categories]);
    }

    #[Route('/new', name: 'app_ingredient_category_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $category = new IngredientCategory();
        $form = $this->createForm(IngredientCategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->managePosition($category);
            $this->repository->add($category, true);

            return $this->redirectToRoute('app_ingredient_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient_category/new.html.twig', [
            'category' => $category,
            'form'     => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ingredient_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, IngredientCategory $category): Response
    {
        $beforeCategory = $this->repository->findBeforeCategory($category);
        if ($beforeCategory) {
            $category->setPositionEnum(IngredientCategory::POSITION_AFTER);
            $category->setBeforeCategory($beforeCategory);
        } else {
            $category->setPositionEnum(IngredientCategory::POSITION_FIRST);
        }

        $form = $this->createForm(IngredientCategoryType::class, $category, ['currentCategoryId' => $category->getId()]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->managePosition($category, $category);
            $this->repository->add($category, true);

            return $this->redirectToRoute('app_ingredient_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient_category/edit.html.twig', [
            'category' => $category,
            'form'     => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ingredient_category_delete', methods: ['POST'])]
    public function delete(Request $request, IngredientCategory $category): Response
    {
        if (
            $this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))
            && 0 === $category->getIngredients()->count()
        ) {
            $this->repository->remove($category, true);
        }

        return $this->redirectToRoute('app_ingredient_category_index', [], Response::HTTP_SEE_OTHER);
    }

    private function managePosition(IngredientCategory $category, ?IngredientCategory $currentCategory = null)
    {
        switch ($category->getPositionEnum()) {
            case 'first':
                $firstCategoryPosition = $this->repository->findFirstCategoryPosition($currentCategory);
                $category->setPosition($firstCategoryPosition - 1);
                break;
            case 'last':
                $lastCategoryPosition = $this->repository->findLastCategoryPosition($currentCategory);
                $category->setPosition($lastCategoryPosition + 1);
                break;
            case 'after':
                $res = $this->repository->findCategoryPositionWithNextOne($category->getBeforeCategory(), $currentCategory);
                $pos1 = $res[0]['position'];
                $pos2 = isset($res[1]) ? $res[1]['position'] : $pos1+1;
                $category->setPosition(($pos1+$pos2)/2);
                break;
        }
    }
}

src/Controller/Ingredient/IngredientController.php
<?php

namespace App\Controller\Ingredient;

use App\Entity\Ingredient;
use App\Entity\IngredientFilters;
use App\Form\IngredientFiltersType;
use App\Form\IngredientType;
use App\Repository\IngredientRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ingredient')]
class IngredientController extends AbstractController
{
    const PER_PAGE_OPTIONS = [10, 25, 50, 100];
    const DEFAULT_PER_PAGE_OPTION = 25;

    private IngredientRepository $repository;

    public function __construct(IngredientRepository $repository)
    {
        $this->repository = $repository;
    }

    #[Route('/', name: 'app_ingredient_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $numItemsPerPage = $request->query->getInt('numItemsPerPage', self::DEFAULT_PER_PAGE_OPTION);

        $ingredientFilters = new IngredientFilters();
        $formFilters = $this->createForm(IngredientFiltersType::class, $ingredientFilters, ['method' => 'GET']);
        $formFilters->handleRequest($request);

        $query = $this->repository->findAllQuery($ingredientFilters);

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            $numItemsPerPage
        );

        return $this->render('ingredient/index.html.twig', [
            'ingredients'        => $this->repository->findAll(),
            'pagination'         => $pagination,
            'numItemsPerPage'    => $numItemsPerPage,
            'perPageOptions'     => self::PER_PAGE_OPTIONS,
            'ingredientFilters'  => $ingredientFilters,
            'formFilters'        => $formFilters->createView(),
        ]);
    }

    #[Route('/new', name: 'app_ingredient_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $ingredient = new Ingredient();
        $form = $this->createForm(IngredientType::class, $ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($ingredient, true);

            return $this->redirectToRoute('app_ingredient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient/new.html.twig', [
            'ingredient' => $ingredient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ingredient_show', methods: ['GET'])]
    public function show(Ingredient $ingredient): Response
    {
        return $this->render('ingredient/show.html.twig', [
            'ingredient' => $ingredient,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ingredient_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ingredient $ingredient): Response
    {
        $form = $this->createForm(IngredientType::class, $ingredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($ingredient, true);

            return $this->redirectToRoute('app_ingredient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient/edit.html.twig', [
            'ingredient' => $ingredient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ingredient_delete', methods: ['POST'])]
    public function delete(Request $request, Ingredient $ingredient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ingredient->getId(), $request->request->get('_token'))) {
            $this->repository->remove($ingredient, true);
        }

        return $this->redirectToRoute('app_ingredient_index', [], Response::HTTP_SEE_OTHER);
    }
}

src/Controller/Ingredient/IngredientTagController.php
<?php

namespace App\Controller\Ingredient;

use App\Entity\IngredientTag;
use App\Form\IngredientTagType;
use App\Repository\IngredientTagRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/ingredient-tag')]
class IngredientTagController extends AbstractController
{
    private IngredientTagRepository $repository;

    public function __construct(IngredientTagRepository $repository)
    {
        $this->repository = $repository;
    }

    #[Route('/', name: 'app_ingredient_tag_index', methods: ['GET'])]
    public function index(): Response
    {
        $tags = $this->repository->findBy([], ['name' => 'ASC']);

        return $this->render('ingredient_tag/index.html.twig', ['tags' => $tags]);
    }

    #[Route('/new', name: 'app_ingredient_tag_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $tag = new IngredientTag();
        $form = $this->createForm(IngredientTagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($tag, true);

            return $this->redirectToRoute('app_ingredient_tag_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient_tag/new.html.twig', [
            'tag'  => $tag,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ingredient_tag_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, IngredientTag $tag): Response
    {
        $form = $this->createForm(IngredientTagType::class, $tag);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($tag, true);

            return $this->redirectToRoute('app_ingredient_tag_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('ingredient_tag/edit.html.twig', [
            'tag'  => $tag,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ingredient_tag_delete', methods: ['POST'])]
    public function delete(Request $request, IngredientTag $tag): Response
    {
        if ($this->isCsrfTokenValid('delete'.$tag->getId(), $request->request->get('_token'))) {
            $this->repository->remove($tag, true);
        }

        return $this->redirectToRoute('app_ingredient_tag_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/ingredient/_delete_form.html.twig
<div class="modal fade" id="modalDeleteIngredient{{ ingredient.id }}" tabindex="-1"
     aria-labelledby="Supprimer un ingrédient" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Supprimer un ingrédient">Suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                Supprimer l'ingrédient "{{ ingredient.name }}" ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post"
                      action="{{ path('app_ingredient_delete', {'id': ingredient.id}) }}"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ingredient.id) }}">
                    <button class="btn btn-primary">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/ingredient/_filters.html.twig
{% form_theme formFilters 'bootstrap_5_horizontal_layout.html.twig' %}

{{ form_start(formFilters) }}

{{ form_row(formFilters.name) }}
{{ form_row(formFilters.category) }}
{{ form_row(formFilters.tags) }}
{{ form_row(formFilters.whereToKeep) }}

<input type="hidden" name="numItemsPerPage" value="{{ numItemsPerPage }}">

<div class="row align-items-center justify-content-end mt-2">
    <div class="col-sm-10">
        {{ form_widget(formFilters.save) }}

        <a class="btn btn-sm btn-outline-secondary"
           href="{{ path('app_ingredient_index', {'numItemsPerPage': numItemsPerPage}) }}"
        >
            Réinitialiser
        </a>
    </div>
</div>

{{ form_end(formFilters) }}

templates/ingredient/_form.html.twig
{{ form_start(form) }}
<div class="card">
    <div class="card-header">
        <h1 class="display-6">{{ title }}</h1>
    </div>
    <div class="card-body">
        {{ form_errors(form) }}

        {{ form_row(form.name) }}
        {{ form_row(form.category) }}
        {{ form_row(form.whereToKeep) }}
        {{ form_row(form.tags) }}
    </div>
    <div class="card-footer">
        {{ form_widget(form.save, {'label': submit_label}) }}
        <a class="btn btn-secondary" href="{{ path('app_ingredient_index') }}" role="button">Retour</a>
    </div>
</div>
{{ form_end(form) }}

templates/ingredient/_items_per_page.html.twig
<span>Nombre d'ingrédients par page : </span>

<nav aria-label="Nombre d'ingrédients affichés par page" class="d-inline-block">
    <ul class="pagination mb-0">
        {% for perPageOption in perPageOptions %}
            {% if numItemsPerPage == perPageOption %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ perPageOption }}
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{
                        path('app_ingredient_index', app.request.query.all|merge({
                            'numItemsPerPage': perPageOption,
                            'page': 1
                        }))
                    }}">
                        {{ perPageOption }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

templates/ingredient/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un ingrédient{% endblock %}

{% block content %}
    {{ include('ingredient/_form.html.twig', {
        'title': 'Modifier un ingrédient',
        'submit_label': 'Modifier'
    }) }}
{% endblock %}

templates/ingredient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des ingrédients{% endblock %}

{% block content %}
<div class="row row-cols-auto align-items-center">
    <div class="col">
        <h1 class="display-6">Liste des ingrédients</h1>
    </div>
    <div class="col">
        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_ingredient_new') }}" role="button">Nouvel ingrédient</a>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card text-bg-light my-2">
            <div class="card-body">
                {{ include('ingredient/_filters.html.twig') }}
            </div>
        </div>
    </div>
</div>

<div class="row mt-2 mb-3 align-items-center">
    <div class="col">
        {% if pagination.getTotalItemCount == 0 %}
            Aucun ingrédient trouvé
        {% elseif pagination.getTotalItemCount == 1 %}
            1 ingrédient trouvé
        {% else %}
            {{ pagination.getTotalItemCount|number_format }} ingrédients trouvés
        {% endif %}
    </div>
    <div class="col text-end">
        {{ include('ingredient/_items_per_page.html.twig') }}
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table table-hover align-middle table-bordered">
            <thead class="table-light">
                <tr>
                    <th scope="col" {% if pagination.isSorted('c.name') %}class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination, 'Catégorie', 'c.name') }}
                    </th>
                    <th scope="col" {% if pagination.isSorted('i.name') %}class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination, 'Nom', 'i.name') }}
                    </th>
                    <th scope="col">Tags</th>
                    <th scope="col">Conservation</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for ingredient in pagination %}
                <tr>
                    <td>{{ ingredient.category.name }}</td>
                    <td>{{ ingredient.name }}</td>
                    <td>
                        {% for tag in ingredient.tags %}
                            <span class="badge bg-secondary fs-6 fw-normal">{{ tag.name }}</span>
                        {% endfor %}
                    </td>
                    <td>{{ ingredient.whereToKeepLabel }}</td>
                    <td>
                        <a class="btn btn-sm btn-outline-primary"
                           href="{{ path('app_ingredient_show', {'id': ingredient.id}) }}"
                        >
                            voir
                        </a>
                        <a class="btn btn-sm btn-outline-secondary"
                           href="{{ path('app_ingredient_edit', {'id': ingredient.id}) }}"
                        >
                            modifier
                        </a>
                        <button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                                data-bs-target="#modalDeleteIngredient{{ ingredient.id }}"
                        >
                            supprimer
                        </button>

                        {{ include('ingredient/_delete_form.html.twig', {'ingredient': ingredient}) }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Aucun ingrédient trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</div>
{% endblock %}

templates/ingredient/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel ingrédient{% endblock %}

{% block content %}
    {{ include('ingredient/_form.html.twig', {
        'title': 'Nouvel ingrédient',
        'submit_label': 'Créer'
    }) }}
{% endblock %}

templates/ingredient/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ingrédient{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h1 class="display-6">Ingrédient</h1>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-2">Nom :</dt>
                <dd class="col-sm-10">{{ ingredient.name }}</dd>

                <dt class="col-sm-2">Catégorie :</dt>
                <dd class="col-sm-10">{{ ingredient.category }}</dd>

                <dt class="col-sm-2">Type de quantité :</dt>
                <dd class="col-sm-10">
                    {% if ingredient.defaultQuantityType  %}
                        {{ ingredient.defaultQuantityType }}
                    {% else %}
                        <span class="badge text-bg-light">Aucun</span>
                    {% endif %}
                </dd>

                <dt class="col-sm-2">Tags :</dt>
                <dd class="col-sm-10">
                    {% for tag in ingredient.tags %}
                        <span class="badge bg-secondary fs-6 fw-normal">{{ tag }}</span>
                    {% else %}
                        <span class="badge text-bg-light">Aucun</span>
                    {% endfor %}
                </dd>

                <dt class="col-sm-2">Conservation :</dt>
                <dd class="col-sm-10">
                    {% if ingredient.whereToKeepLabel  %}
                        {{ ingredient.whereToKeepLabel }}
                    {% else %}
                        <span class="badge text-bg-light">Inconnue</span>
                    {% endif %}
                </dd>
            </dl>
        </div>
        <div class="card-footer">
            <a class="btn btn-primary"
               href="{{ path('app_ingredient_edit', {'id': ingredient.id}) }}"
               role="button"
            >Modifier</a>

            {% set referer = app.request.headers.get('referer')|default(path('app_ingredient_index')) %}
            <a class="btn btn-secondary" href="{{ referer }}" role="button">Retour</a>
        </div>
    </div>
{% endblock %}