src/Entity/StockIngredient.php
<?php

namespace App\Entity;

use App\Repository\StockIngredientRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: StockIngredientRepository::class)]
class StockIngredient
{
    const STOCK_STATUS_OPTIONS = [
        'soon_out_of_stock' => 'Bientôt épuisé(e)',
        'out_of_stock' => 'Épuisé(e)',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'stockIngredients')]
    #[ORM\JoinColumn(nullable: false)]
    #[Assert\NotNull(message: "L'ingrédient est requis.")]
    #[Assert\Type(type: Ingredient::class, message: "Cette valeur n'est pas du bon type.")]
    #[Assert\Valid]
    private ?Ingredient $ingredient = null;

    #[ORM\ManyToOne]
    #[Assert\Type(type: QuantityType::class, message: "Cette valeur n'est pas du bon type.")]
    #[Assert\Valid]
    private ?QuantityType $quantityType = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 6, scale: 2, nullable: true, options: ["unsigned" => true])]
    private ?string $quantityNumber = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: "Le commentaire ne peut pas être vide.", allowNull: true, normalizer: 'trim')]
    #[Assert\Length(max: 255, maxMessage: "Le commentaire ne peut excéder 255 caractères.")]
    private ?string $comment = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $expiresAt = null;

    #[ORM\Column(length: 50, nullable: true)]
    #[Assert\Choice(callback: 'getStockStatusOptions', message: 'Cette option n\'est pas valide.')]
    private ?string $stockStatus = null;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIngredient(): ?Ingredient
    {
        return $this->ingredient;
    }

    public function setIngredient(?Ingredient $ingredient): self
    {
        $this->ingredient = $ingredient;

        return $this;
    }

    public function getQuantityType(): ?QuantityType
    {
        return $this->quantityType;
    }

    public function setQuantityType(?QuantityType $quantityType): self
    {
        $this->quantityType = $quantityType;

        return $this;
    }

    public function getQuantityNumber(): ?string
    {
        return $this->quantityNumber;
    }

    public function setQuantityNumber(?string $quantityNumber): self
    {
        $this->quantityNumber = $quantityNumber;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getExpiresAt(): ?\DateTimeInterface
    {
        return $this->expiresAt;
    }

    public function setExpiresAt(?\DateTimeInterface $expiresAt): self
    {
        $this->expiresAt = $expiresAt;

        return $this;
    }

    public function getStockStatus(): ?string
    {
        return $this->stockStatus;
    }

    public function setStockStatus(?string $stockStatus): self
    {
        $this->stockStatus = $stockStatus;

        return $this;
    }

    public static function getStockStatusOptions(): array
    {
        return array_merge(
            ['-' => null],
            array_flip(self::STOCK_STATUS_OPTIONS)
        );
    }

    public function getStockStatusLabel(): ?string
    {
        if ($this->stockStatus) {
            return self::STOCK_STATUS_OPTIONS[$this->stockStatus];
        }

        return null;
    }
}

src/Form/StockIngredientType.php
<?php

namespace App\Form;

use App\Entity\Ingredient;
use App\Entity\QuantityType;
use App\Entity\StockIngredient;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StockIngredientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('ingredient', EntityType::class, [
                'label' => 'Ingrédient',
                'class' => Ingredient::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('i')->orderBy('i.name', 'ASC');
                },
                'attr' => ['class' => 'select2'],
            ])
            ->add('quantityNumber', NumberType::class, [
                'label' => 'Quantité',
                'required' => false,
            ])
            ->add('quantityType', EntityType::class, [
                'label' => 'Mesure',
                'required' => false,
                'class' => QuantityType::class,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('q')->orderBy('q.name', 'ASC');
                },
            ])
            ->add('expiresAt', DateType::class, [
                'label' => "Date d'expiration",
                'required' => false,
                'years' => range(intval(date('Y'))-1, intval(date('Y'))+6),
            ])
            ->add('stockStatus', ChoiceType::class, [
                'label' => 'Statut',
                'choices' => StockIngredient::getStockStatusOptions(),
                'required' => false,
            ])
            ->add('comment', TextType::class, [
                'label' => 'Commentaire',
                'required' => false,
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => StockIngredient::class,
        ]);
    }
}

src/Controller/StockIngredientController.php
<?php

namespace App\Controller;

use App\Entity\StockIngredient;
use App\Entity\StockIngredientFilters;
use App\Form\StockIngredientFiltersType;
use App\Form\StockIngredientType;
use App\Repository\StockIngredientRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/stock-ingredient')]
class StockIngredientController extends AbstractController
{
    const PER_PAGE_OPTIONS = [10, 25, 50, 100];
    const DEFAULT_PER_PAGE_OPTION = 25;

    private StockIngredientRepository $repository;

    public function __construct(StockIngredientRepository $repository)
    {
        $this->repository = $repository;
    }

    #[Route('/', name: 'app_stock_ingredient_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $numItemsPerPage = $request->query->getInt('numItemsPerPage', self::DEFAULT_PER_PAGE_OPTION);

        $stockIngredientFilters = new StockIngredientFilters();
        $formFilters = $this->createForm(StockIngredientFiltersType::class, $stockIngredientFilters, ['method' => 'GET']);
        $formFilters->handleRequest($request);

        $query = $this->repository->findAllQuery($stockIngredientFilters);

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            $numItemsPerPage
        );

        return $this->render('stock_ingredient/index.html.twig', [
            'pagination'             => $pagination,
            'numItemsPerPage'        => $numItemsPerPage,
            'perPageOptions'         => self::PER_PAGE_OPTIONS,
            'stockIngredientFilters' => $stockIngredientFilters,
            'formFilters'            => $formFilters->createView(),
        ]);
    }

    #[Route('/new', name: 'app_stock_ingredient_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $stockIngredient = new StockIngredient();
        $form = $this->createForm(StockIngredientType::class, $stockIngredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($stockIngredient, true);

            return $this->redirectToRoute('app_stock_ingredient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('stock_ingredient/new.html.twig', [
            'stockIngredient'  => $stockIngredient,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_stock_ingredient_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, StockIngredient $stockIngredient): Response
    {
        $form = $this->createForm(StockIngredientType::class, $stockIngredient);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($stockIngredient, true);

            return $this->redirectToRoute('app_stock_ingredient_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('stock_ingredient/edit.html.twig', [
            'stockIngredient' => $stockIngredient,
            'form'            => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_stock_ingredient_delete', methods: ['POST'])]
    public function delete(Request $request, StockIngredient $stockIngredient): Response
    {
        if ($this->isCsrfTokenValid('delete'.$stockIngredient->getId(), $request->request->get('_token'))) {
            $this->repository->remove($stockIngredient, true);
        }

        return $this->redirectToRoute('app_stock_ingredient_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/stock_ingredient/_delete_form.html.twig
<div class="modal fade" id="modalDeleteStockIngredient{{ stockIngredient.id }}" tabindex="-1"
     aria-labelledby="Supprimer un ingrédient" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Supprimer un ingrédient">Suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                Supprimer l'ingrédient "{{ stockIngredient.ingredient.name }}" ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post"
                      action="{{ path('app_stock_ingredient_delete', {'id': stockIngredient.id}) }}"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stockIngredient.id) }}">
                    <button class="btn btn-primary">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/stock_ingredient/_filters.html.twig
{% form_theme formFilters 'bootstrap_5_horizontal_layout.html.twig' %}

{{ form_start(formFilters) }}

{{ form_row(formFilters.name) }}
{{ form_row(formFilters.category) }}

<input type="hidden" name="numItemsPerPage" value="{{ numItemsPerPage }}">

<div class="row align-items-center justify-content-end mt-2">
    <div class="col-sm-10">
        {{ form_widget(formFilters.save) }}

        <a class="btn btn-sm btn-outline-secondary"
           href="{{ path('app_stock_ingredient_index', {'numItemsPerPage': numItemsPerPage}) }}"
        >
            Réinitialiser
        </a>
    </div>
</div>

{{ form_end(formFilters) }}

templates/stock_ingredient/_form.html.twig
{{ form_start(form) }}
<div class="card">
    <div class="card-header">
        <h1 class="display-6">{{ title }}</h1>
    </div>
    <div class="card-body">
        {{ form_errors(form) }}

        {{ form_row(form.ingredient) }}
        {{ form_row(form.quantityNumber) }}
        {{ form_row(form.quantityType) }}

        <div class="row">
            <div class="col-3">
                {{ form_row(form.expiresAt) }}
            </div>
        </div>

        {{ form_row(form.stockStatus) }}
        {{ form_row(form.comment) }}
    </div>
    <div class="card-footer">
        {{ form_widget(form.save, {'label': submit_label}) }}
        <a class="btn btn-secondary" href="{{ path('app_stock_ingredient_index') }}" role="button">Retour</a>
    </div>
</div>
{{ form_end(form) }}

templates/stock_ingredient/_items_per_page.html.twig
<span>Nombre d'ingrédients par page : </span>

<nav aria-label="Nombre d'ingrédients affichés par page" class="d-inline-block">
    <ul class="pagination mb-0">
        {% for perPageOption in perPageOptions %}
            {% if numItemsPerPage == perPageOption %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ perPageOption }}
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{
                        path('app_stock_ingredient_index', app.request.query.all|merge({
                            'numItemsPerPage': perPageOption,
                            'page': 1
                        }))
                    }}">
                        {{ perPageOption }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

templates/stock_ingredient/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un ingrédient en stock{% endblock %}

{% block content %}
    {{ include('stock_ingredient/_form.html.twig', {
        'title': 'Modifier un ingrédient',
        'submit_label': 'Modifier'
    }) }}
{% endblock %}

templates/stock_ingredient/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des ingrédients en stock{% endblock %}

{% block content %}
<div class="row row-cols-auto align-items-center">
    <div class="col">
        <h1 class="display-6">Liste des ingrédients en stock</h1>
    </div>
    <div class="col">
        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_stock_ingredient_new') }}" role="button">
            Nouvel ingrédient
        </a>
    </div>
</div>


<div class="row">
    <div class="col">
        <div class="card text-bg-light my-2">
            <div class="card-body">
                {{ include('stock_ingredient/_filters.html.twig') }}
            </div>
        </div>
    </div>
</div>

<div class="row mt-2 mb-3 align-items-center">
    <div class="col">
        {% if pagination.getTotalItemCount == 0 %}
            Aucun ingrédient trouvé
        {% elseif pagination.getTotalItemCount == 1 %}
            1 ingrédient trouvé
        {% else %}
            {{ pagination.getTotalItemCount|number_format }} ingrédients trouvés
        {% endif %}
    </div>
    <div class="col text-end">
        {{ include('stock_ingredient/_items_per_page.html.twig') }}
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table table-hover align-middle table-bordered">
            <thead class="table-light">
            <tr>
                <th scope="col" {% if pagination.isSorted('c.name') %}class="sorted"{% endif %}>
                    {{ knp_pagination_sortable(pagination, 'Catégorie', 'c.name') }}
                </th>
                <th scope="col" {% if pagination.isSorted('i.name') %}class="sorted"{% endif %}>
                    {{ knp_pagination_sortable(pagination, 'Nom', 'i.name') }}
                </th>
                <th scope="col">Quantité</th>
                <th scope="col" {% if pagination.isSorted(['expiresAtIsNull', 'si.expiresAt']) %}class="sorted"{% endif %}>
                    {{ knp_pagination_sortable(pagination, "Date d'expiration", ['expiresAtIsNull', 'si.expiresAt']) }}
                </th>
                <th scope="col" {% if pagination.isSorted(['stockStatusIsNull', 'si.stockStatus']) %}class="sorted"{% endif %}>
                    {{ knp_pagination_sortable(pagination, "Statut", ['stockStatusIsNull', 'si.stockStatus']) }}
                </th>
                <th scope="col">Commentaire</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for stockIngredient in pagination %}
                <tr>
                    <td>{{ stockIngredient.ingredient.category.name }}</td>
                    <td>{{ stockIngredient.ingredient.name }}</td>
                    <td>
                        {% if stockIngredient.quantityNumber is not null %}
                            {{ stockIngredient.quantityNumber|format_number }}
                            {% if stockIngredient.quantityType is not null %}
                                {%
                                    if stockIngredient.quantityNumber > 1
                                    and stockIngredient.quantityType.pluralName is not null
                                %}
                                    {{ stockIngredient.quantityType.pluralName }}
                                {% else %}
                                    {{ stockIngredient.quantityType.name }}
                                {% endif %}
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>
                        {% if stockIngredient.expiresAt is not null %}
                            {{ stockIngredient.expiresAt|alertRemainingDate|raw }}
                            {{ stockIngredient.expiresAt|remainingDate }}
                            <span class="text-secondary fw-light">({{ stockIngredient.expiresAt|date('d/m/Y') }})</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if stockIngredient.stockStatus is not null %}
                            <span class="badge bg-danger fs-6 fw-normal">{{ stockIngredient.stockStatusLabel }}</span>
                        {% endif %}
                    </td>
                    <td>{{ stockIngredient.comment }}</td>
                    <td>
                        <a class="btn btn-sm btn-outline-secondary"
                           href="{{ path('app_stock_ingredient_edit', {'id': stockIngredient.id}) }}"
                        >
                            modifier
                        </a>
                        <button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                                data-bs-target="#modalDeleteStockIngredient{{ stockIngredient.id }}"
                        >
                            supprimer
                        </button>

                        {{ include('stock_ingredient/_delete_form.html.twig', {'stockIngredient': stockIngredient}) }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucun ingrédient trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</div>
{% endblock %}

templates/stock_ingredient/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel ingrédient en stock{% endblock %}

{% block content %}
    {{ include('stock_ingredient/_form.html.twig', {
        'title': 'Nouvel ingrédient',
        'submit_label': 'Créer'
    }) }}
{% endblock %}