src/Entity/Recipe.php
<?php

namespace App\Entity;

use App\Repository\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: RecipeIngredient::class, cascade: ['persist', 'remove'])]
    private Collection $recipeIngredients;

    #[ORM\OneToMany(mappedBy: 'recipe', targetEntity: RecipeStep::class, cascade: ['persist', 'remove'])]
    private Collection $recipeSteps;

    /**
     * @var Collection<int, RecipePortionNumber>
     */
    private Collection $portions;

    public function __construct()
    {
        $this->recipeIngredients = new ArrayCollection();
        $this->recipeSteps = new ArrayCollection();

        $this->hydratePortions();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return Collection<int, RecipeIngredient>
     */
    public function getRecipeIngredients(): Collection
    {
        return $this->recipeIngredients;
    }

    public function addRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if (!$this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients->add($recipeIngredient);
            $recipeIngredient->setRecipe($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(RecipeIngredient $recipeIngredient): self
    {
        if ($this->recipeIngredients->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getRecipe() === $this) {
                $recipeIngredient->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RecipeStep>
     */
    public function getRecipeSteps(): Collection
    {
        return $this->recipeSteps;
    }

    public function addRecipeStep(RecipeStep $recipeStep): self
    {
        if (!$this->recipeSteps->contains($recipeStep)) {
            $this->recipeSteps->add($recipeStep);
            $recipeStep->setRecipe($this);
        }

        return $this;
    }

    public function removeRecipeStep(RecipeStep $recipeStep): self
    {
        if ($this->recipeSteps->removeElement($recipeStep)) {
            // set the owning side to null (unless already changed)
            if ($recipeStep->getRecipe() === $this) {
                $recipeStep->setRecipe(null);
            }
        }

        return $this;
    }

    public function hydratePortions(): self
    {
        $ingredientsByPortions = [];

        foreach ($this->getRecipeIngredients() as $recipeIngredient) {
            foreach($recipeIngredient->getPortionNumbers() as $recipeIngredientPortionNumber) {
                if (!isset($ingredientsByPortions[$recipeIngredientPortionNumber->getPortionNumber()])) {
                    $ingredientsByPortions[$recipeIngredientPortionNumber->getPortionNumber()] = [];
                }
                $ingredientsByPortions[$recipeIngredientPortionNumber->getPortionNumber()][] = $recipeIngredientPortionNumber;
            }
        }

        $this->setPortions(new ArrayCollection());
        foreach ($ingredientsByPortions as $portionNumber => $ingredientsByPortion) {
            $recipePortionNumber = (new RecipePortionNumber())->setPortionNumber($portionNumber);
            foreach ($ingredientsByPortion as $ingredient) {
                $recipePortionNumber->addRecipeIngredientPortionNumber($ingredient);
            }
            $this->addPortion($recipePortionNumber);
        }

        return $this;
    }

    /**
     * @return Collection<int, RecipePortionNumber>
     */
    public function getPortions(): Collection
    {
        return $this->portions;
    }

    /**
     * @param Collection<int, RecipePortionNumber> $portions
     * @return Recipe
     */
    public function setPortions(Collection $portions): self
    {
        $this->portions = $portions;

        return $this;
    }

    public function addPortion(RecipePortionNumber $portion): self
    {
        if (!$this->portions->contains($portion)) {
            $this->portions->add($portion);
            $portion->setRecipe($this);
        }

        return $this;
    }

    public function removePortion(RecipePortionNumber $portion): self
    {
        if ($this->portions->removeElement($portion)) {
            // set the owning side to null (unless already changed)
            if ($portion->getRecipe() === $this) {
                $portion->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return array<int>
     */
    public function getPortionNumberList(): array
    {
        return $this->getPortions()->map(function(RecipePortionNumber $e) {
            return $e->getPortionNumber();
        })->toArray();
    }
}

src/Form/RecipeType.php
<?php

namespace App\Form;

use App\Entity\Recipe;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecipeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
            ])
            ->add('recipeIngredients', CollectionType::class, [
                'label' => 'Ingrédients',
                'label_attr' => ['class' => 'visually-hidden'],
                'entry_type' => RecipeIngredientType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ])
            ->add('recipeSteps', CollectionType::class, [
                'label' => 'Étapes',
                'label_attr' => ['class' => 'visually-hidden'],
                'entry_type' => RecipeStepType::class,
                'entry_options' => ['label' => false],
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipe::class,
        ]);
    }
}

src/Controller/RecipeController.php
<?php

namespace App\Controller;

use App\Entity\AddRecipePortionNumber;
use App\Entity\Recipe;
use App\Entity\RecipeFilters;
use App\Entity\RecipeIngredient;
use App\Entity\RecipeIngredientPortionNumber;
use App\Entity\RecipePortionNumber;
use App\Entity\RecipeStep;
use App\Form\AddRecipePortionNumberType;
use App\Form\RecipeFiltersType;
use App\Form\RecipeIngredientPortionNumberType;
use App\Form\RecipeByPortionType;
use App\Form\RecipePortionNumberType;
use App\Form\RecipeType;
use App\Repository\RecipeIngredientPortionNumberRepository;
use App\Repository\RecipeIngredientRepository;
use App\Repository\RecipeRepository;
use App\Repository\RecipeStepRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/recipe')]
class RecipeController extends AbstractController
{
    const PER_PAGE_OPTIONS = [10, 25, 50, 100];
    const DEFAULT_PER_PAGE_OPTION = 25;

    private RecipeRepository $repository;
    private RecipeIngredientPortionNumberRepository $recipeIngredientPortionNumberRepository;

    public function __construct(
        RecipeRepository $repository,
        RecipeIngredientPortionNumberRepository $recipeIngredientPortionNumberRepository
    )
    {
        $this->repository = $repository;
        $this->recipeIngredientPortionNumberRepository = $recipeIngredientPortionNumberRepository;
    }

    #[Route('/', name: 'app_recipe_index', methods: ['GET'])]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $numItemsPerPage = $request->query->getInt('numItemsPerPage', self::DEFAULT_PER_PAGE_OPTION);

        $recipeFilters = new RecipeFilters();
        $formFilters = $this->createForm(RecipeFiltersType::class, $recipeFilters, ['method' => 'GET']);
        $formFilters->handleRequest($request);

        $query = $this->repository->findAllQuery($recipeFilters);

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            $numItemsPerPage
        );

        return $this->render('recipe/index.html.twig', [
            'recipes'         => $this->repository->findAll(),
            'pagination'      => $pagination,
            'numItemsPerPage' => $numItemsPerPage,
            'perPageOptions'  => self::PER_PAGE_OPTIONS,
            'recipeFilters'   => $recipeFilters,
            'formFilters'     => $formFilters->createView(),
        ]);
    }

    #[Route('/new', name: 'app_recipe_new', methods: ['GET', 'POST'])]
    public function new(Request $request): Response
    {
        $recipe = (new Recipe())->addRecipeStep((new RecipeStep()));

        foreach (range(0, 2) as $index) {
            $recipe->addRecipeIngredient(new RecipeIngredient());
        }

        $form = $this->createForm(RecipeType::class, $recipe);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($recipe, true);

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipe/new.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipe_show', methods: ['GET'])]
    public function show(int $id): Response
    {
        $recipe = $this->repository->findWithIngredientsAndSteps($id);

        if (null === $recipe) {
            throw $this->createNotFoundException("Aucune recette trouvée pour l'id ".$id);
        }

        return $this->render('recipe/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recipe_edit', methods: ['GET', 'POST'])]
    public function edit(
        int $id,
        Request $request,
        RecipeIngredientRepository $recipeIngredientRepository,
        RecipeStepRepository $recipeStepRepository,
    ): Response
    {
        $recipe = $this->repository->findWithIngredientsAndSteps($id);

        if (null === $recipe) {
            throw $this->createNotFoundException("Aucune recette trouvée pour l'id ".$id);
        }

        $form = $this->createForm(RecipeType::class, $recipe);

        $originalRecipeIngredients = new ArrayCollection();
        foreach ($recipe->getRecipeIngredients() as $recipeIngredient) {
            $originalRecipeIngredients->add($recipeIngredient);
        }

        $originalRecipeSteps = new ArrayCollection();
        foreach ($recipe->getRecipeSteps() as $recipeStep) {
            $originalRecipeSteps->add($recipeStep);
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            foreach ($originalRecipeIngredients as $recipeIngredient) {
                if (false === $recipe->getRecipeIngredients()->contains($recipeIngredient)) {
                    $recipeIngredientRepository->remove($recipeIngredient);
                }
            }
            foreach ($originalRecipeSteps as $recipeStep) {
                if (false === $recipe->getRecipeSteps()->contains($recipeStep)) {
                    $recipeStepRepository->remove($recipeStep);
                }
            }

            $this->repository->add($recipe, true);

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipe/edit.html.twig', [
            'recipe' => $recipe,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_recipe_delete', methods: ['POST'])]
    public function delete(Request $request, Recipe $recipe): Response
    {
        if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
            $this->repository->remove($recipe, true);
        }

        return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/add-portion-number', name: 'app_recipe_add_portion_number', methods: ['GET', 'POST'])]
    public function addPortionNumber(Request $request, Recipe $recipe): Response
    {
        $addRecipePortionNumber =  new AddRecipePortionNumber();

        $form = $this->createForm(AddRecipePortionNumberType::class, $addRecipePortionNumber);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $portionNumber = $addRecipePortionNumber->getPortionNumber();

            foreach($recipe->getRecipeIngredients() as $recipeIngredient) {
                $recipeIngredientPortionNumber = (new RecipeIngredientPortionNumber())
                    ->setRecipeIngredient($recipeIngredient)
                    ->setPortionNumber($portionNumber)
                ;

                $this->recipeIngredientPortionNumberRepository->add($recipeIngredientPortionNumber, true);
            }

            return $this->redirectToRoute(
                'app_recipe_manage_portion_number',
                [
                    'id'                     => $recipe->getId(),
                    'default-portion-number' => $portionNumber,
                ],
                Response::HTTP_SEE_OTHER
            );
        }

        return $this->renderForm('recipe/add_portion_number.html.twig', [
            'recipe' => $recipe,
            'form'   => $form,
        ]);
    }

    #[Route('/{id}/manage-portion-number', name: 'app_recipe_manage_portion_number', methods: ['GET', 'POST'])]
    public function managePortionNumber(Recipe $recipe, Request $request): Response
    {
        $defaultPortionNumber = (int) $request->query->get('default-portion-number');

        $recipe->hydratePortions();

        if ($recipe->getPortions()->count() === 0) {
            throw new BadRequestHttpException("Cette recette n'a pas de portions.");
        }

        if (0 === $defaultPortionNumber || !in_array($defaultPortionNumber, $recipe->getPortionNumberList())) {
            $defaultPortionNumber = array_key_first($recipe->getPortionNumberList());
        }

        $form = $this->createForm(RecipeByPortionType::class, $recipe);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->repository->add($recipe, true);

            return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('recipe/manage_portion_number.html.twig', [
            'recipe'               => $recipe,
            'form'                 => $form,
            'defaultPortionNumber' => $defaultPortionNumber,
        ]);
    }

    #[Route('/{id}/delete-portion-number/{portionNumber}', name: 'app_recipe_delete_portion_number', methods: ['POST'])]
    public function deletePortionNumber(Request $request, Recipe $recipe, int $portionNumber): Response
    {
        $tokenName = sprintf('delete%sportionNumber%s', $recipe->getId(), $portionNumber);

        if ($this->isCsrfTokenValid($tokenName, $request->request->get('_token'))) {
            foreach ($recipe->getRecipeIngredients() as $recipeIngredient) {
                foreach($recipeIngredient->getPortionNumbers() as $recipeIngredientPortionNumber) {
                    if ($recipeIngredientPortionNumber->getPortionNumber() == $portionNumber) {
                        $this->recipeIngredientPortionNumberRepository->remove($recipeIngredientPortionNumber, true);
                    }
                }
            }
        }

        return $this->redirectToRoute('app_recipe_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/recipe/_delete_form.html.twig
<div class="modal fade" id="modalDeleteRecipe{{ recipe.id }}" tabindex="-1"
     aria-labelledby="Supprimer une recette" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Supprimer une recette">Suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                Supprimer la recette "{{ recipe.title }}" ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post"
                      action="{{ path('app_recipe_delete', {'id': recipe.id}) }}"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
                    <button class="btn btn-primary">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/recipe/_delete_portion_number_form.html.twig
<div class="modal fade" id="modalDeletePortionNumber{{ portionNumber }}" tabindex="-1"
     aria-labelledby="Supprimer un nombre de portions" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="Supprimer un nombre de portions">Suppression</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
            </div>
            <div class="modal-body">
                Supprimer le nombre de portions "{{ portionNumber }}" pour la recette "{{ recipe.title }}" ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annuler</button>
                <form method="post"
                      action="{{ path('app_recipe_delete_portion_number', {'id': recipe.id, 'portionNumber': portionNumber}) }}"
                >
                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id ~ 'portionNumber' ~ portionNumber) }}">
                    <button class="btn btn-primary">Supprimer</button>
                </form>
            </div>
        </div>
    </div>
</div>

templates/recipe/_filters.html.twig
{% form_theme formFilters 'bootstrap_5_horizontal_layout.html.twig' %}

{{ form_start(formFilters) }}

{{ form_row(formFilters.title) }}

<input type="hidden" name="numItemsPerPage" value="{{ numItemsPerPage }}">

<div class="row align-items-center justify-content-end mt-2">
    <div class="col-sm-10">
        {{ form_widget(formFilters.save) }}

        <a class="btn btn-sm btn-outline-secondary"
           href="{{ path('app_recipe_index', {'numItemsPerPage': numItemsPerPage}) }}"
        >
            Réinitialiser
        </a>
    </div>
</div>

{{ form_end(formFilters) }}

templates/recipe/_form.html.twig
{% import _self as formMacros %}

{% macro printRecipeIngredientRow(recipeIngredient) %}
    <div class="col-7 pe-1">{{ form_row(recipeIngredient.ingredient) }}</div>
    <div class="col-1 px-1">
        <div class="d-grid">
            <button type="button" class="btn btn-danger btn-sm subformDeleteButton">Supprimer</button>
        </div>
    </div>
{% endmacro %}

{% macro printRecipeStepRow(recipeStep) %}
    <div class="col-2 pe-1 align-self-start">{{ form_row(recipeStep.title) }}</div>
    <div class="col-5 px-1">{{ form_row(recipeStep.description) }}</div>
    <div class="col-1 px-1 my-1 align-self-end">
        <div class="d-grid">
            <button type="button" class="btn btn-danger btn-sm subformDeleteButton">Supprimer</button>
        </div>
    </div>
{% endmacro %}

{{ form_start(form) }}
<div class="card">
    <div class="card-header">
        <h1 class="display-6">{{ title }}</h1>
    </div>
    <div class="card-body">
        {{ form_errors(form) }}

        {{ form_row(form.title) }}
    </div>
    <div class="card-body ingredients">
        <div class="row align-items-center">
            <div class="col-8 pe-1">Ingrédients</div>
        </div>

        <div
            data-index="{{ form.recipeIngredients|length > 0 ? form.recipeIngredients|last.vars.name + 1 : 0 }}"
            data-prototype="{{ formMacros.printRecipeIngredientRow(form.recipeIngredients.vars.prototype)|e('html_attr') }}"
            class="recipeIngredients subformItems mb-2"
        >
            {% for recipeIngredient in form.recipeIngredients %}
                <div class="row align-items-center subformItem">
                    {{ formMacros.printRecipeIngredientRow(recipeIngredient) }}
                </div>
            {% endfor %}
        </div>

        <div class="d-grid col-8">
            <button type="button" class="btn btn-sm btn-secondary add_item_link"
                    data-collection-holder-class="recipeIngredients">
                Ajouter un ingrédient
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="row align-items-center">
            <div class="col-2 pe-1">Titre de l'étape (optionnel)</div>
            <div class="col-5 px-1">Description de l'étape</div>
        </div>

        <div
                data-index="{{ form.recipeSteps|length > 0 ? form.recipeSteps|last.vars.name + 1 : 0 }}"
                data-prototype="{{ formMacros.printRecipeStepRow(form.recipeSteps.vars.prototype)|e('html_attr') }}"
                class="recipeSteps subformItems mb-2"
        >
            {% for recipeStep in form.recipeSteps %}
                <div class="row subformItem">
                    {{ formMacros.printRecipeStepRow(recipeStep) }}
                </div>
            {% endfor %}
        </div>

        <div class="d-grid col-8">
            <button type="button" class="btn btn-sm btn-secondary add_item_link"
                    data-collection-holder-class="recipeSteps">
                Ajouter une étape
            </button>
        </div>
    </div>
    <div class="card-footer">
        {{ form_widget(form.save, {'label': submit_label}) }}
        <a class="btn btn-secondary" href="{{ path('app_recipe_index') }}" role="button">Retour</a>
    </div>
</div>
{{ form_end(form) }}

templates/recipe/_items_per_page.html.twig
<span>Nombre de recettes par page : </span>

<nav aria-label="Nombre de recettes affichées par page" class="d-inline-block">
    <ul class="pagination mb-0">
        {% for perPageOption in perPageOptions %}
            {% if numItemsPerPage == perPageOption %}
                <li class="page-item active">
                    <span class="page-link">
                        {{ perPageOption }}
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="{{
                        path('app_recipe_index', app.request.query.all|merge({
                            'numItemsPerPage': perPageOption,
                            'page': 1
                        }))
                    }}">
                        {{ perPageOption }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>

templates/recipe/add_portion_number.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette : {{ recipe.title }} - Ajouter un nombre de portions{% endblock %}

{% block content %}
    {{ form_start(form) }}
    <div class="card">
        <div class="card-header">
            <h1 class="display-6">Recette : {{ recipe.title }}</h1>
        </div>
        <div class="card-body">
            {{ form_errors(form) }}

            {{ form_row(form.portionNumber) }}
        </div>
        <div class="card-footer">
            {{ form_widget(form.save) }}
            <a class="btn btn-secondary" href="{{ path('app_recipe_index') }}" role="button">Retour</a>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/recipe/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une recette{% endblock %}

{% block content %}
    {{ include('recipe/_form.html.twig', {
        'title': 'Modifier une recette',
        'submit_label': 'Modifier'
    }) }}
{% endblock %}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des recettes{% endblock %}

{% block content %}
<div class="row row-cols-auto align-items-center">
    <div class="col">
        <h1 class="display-6">Liste des recettes</h1>
    </div>
    <div class="col">
        <a class="btn btn-sm btn-outline-primary" href="{{ path('app_recipe_new') }}" role="button">Nouvelle recette</a>
    </div>
</div>

<div class="row">
    <div class="col">
        <div class="card text-bg-light my-2">
            <div class="card-body">
                {{ include('recipe/_filters.html.twig') }}
            </div>
        </div>
    </div>
</div>

<div class="row mt-2 mb-3 align-items-center">
    <div class="col">
        {% if pagination.getTotalItemCount == 0 %}
            Aucune recette trouvée
        {% elseif pagination.getTotalItemCount == 1 %}
            1 recette trouvée
        {% else %}
            {{ pagination.getTotalItemCount|number_format }} recettes trouvées
        {% endif %}
    </div>
    <div class="col text-end">
        {{ include('recipe/_items_per_page.html.twig') }}
    </div>
</div>

<div class="row">
    <div class="col">
        <table class="table table-hover align-middle table-bordered">
            <thead class="table-light">
                <tr>
                    <th scope="col" {% if pagination.isSorted('r.title') %}class="sorted"{% endif %}>
                        {{ knp_pagination_sortable(pagination, 'Recette', 'r.title') }}
                    </th>
{#                    <th>#}
{#                        Nombre de portions#}
{#                    </th>#}
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for recipe in pagination %}
                <tr>
                    <td>{{ recipe.title }}</td>
{#                    <td>{{ recipe.portionNumberList|join(', ') }}</td>#}
                    <td>
                        <a class="btn btn-sm btn-outline-primary"
                           href="{{ path('app_recipe_show', {'id': recipe.id}) }}"
                        >
                            voir
                        </a>
                        <a class="btn btn-sm btn-outline-secondary"
                           href="{{ path('app_recipe_edit', {'id': recipe.id}) }}"
                        >
                            modifier
                        </a>
                        <div class="dropdown d-inline-block">
                            <button class="btn btn-sm btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Portions
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="{{ path('app_recipe_manage_portion_number', {'id': recipe.id}) }}">
                                        Gérer les portions
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{{ path('app_recipe_add_portion_number', {'id': recipe.id}) }}">
                                        Ajouter un nombre de portions
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
                                data-bs-target="#modalDeleteRecipe{{ recipe.id }}"
                        >
                            supprimer
                        </button>
                        {{ include('recipe/_delete_form.html.twig', {'recipe': recipe}) }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Aucune recette trouvée</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
</div>
{% endblock %}

templates/recipe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle recette{% endblock %}

{% block content %}
    {{ include('recipe/_form.html.twig', {
        'title': 'Nouvelle recette',
        'submit_label': 'Créer'
    }) }}
{% endblock %}